{
 "title": "Grafana internal metrics",
 "description": "Provides insights into Grafana itself via internal metrics",
 "tags": [
  "infrastructure",
  "monitoring",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(grafana_build_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Dashboards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_dashboard{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Folders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_folder{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_users{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Admins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_admins{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Process Age",
   "type": "stat",
   "description": "Time since the process started",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{namespace=\"$namespace\"} and on(namespace, pod) grafana_build_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod(s) Scheduled",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (pod) (kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} and on(namespace, pod) grafana_build_info{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Grafana Build Info",
   "type": "table",
   "description": "Build info for this Grafana instance",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(grafana_build_info{namespace=\"$namespace\"}) by (pod, revision, version, goversion, branch)"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Count of Active users",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_active_admins{namespace=\"$namespace\"})",
     "legendFormat": "Active Admins"
    },
    {
     "expr": "max(grafana_stat_totals_active_editors{namespace=\"$namespace\"})",
     "legendFormat": "Active Editors"
    },
    {
     "expr": "max(grafana_stat_totals_active_viewers{namespace=\"$namespace\"})",
     "legendFormat": "Active Viewers"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "description": "Number of times the container has restarted since the pod was created",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Running Version(s)",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(grafana_build_info{namespace=\"$namespace\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Grafana Plugins",
   "type": "table",
   "description": "Lists the running versions for this instance.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(grafana_plugin_build_info{namespace=\"$namespace\"}) by (plugin_id, plugin_type, version, signature_status)"
    }
   ]
  },
  {
   "title": "Total Service Accounts",
   "type": "stat",
   "description": "Total Service Accounts",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_service_accounts{namespace=\"$namespace\"})",
     "legendFormat": "Service Accounts"
    },
    {
     "expr": "max(grafana_stat_total_service_account_tokens{namespace=\"$namespace\"})",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "OOMKills",
   "type": "stat",
   "description": "Number of times Grafana has been oomkilled over the dashboard range",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", container=\"grafana\",reason=\"OOMKilled\",}\n    * on (pod, container)\n        increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"grafana\"}[10m]) > 0\n)"
    }
   ]
  },
  {
   "title": "Process Age",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (pod) (process_start_time_seconds{namespace=\"$namespace\"} and on(namespace, pod) grafana_build_info{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Annotations & Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Alerts by state",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafana_alerting_alerts{namespace=\"$namespace\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alert rule instances (evaluations) by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafana_alerting_alerts{namespace=\"$namespace\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max(sum(grafana_alerting_alerts{namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Alert Request Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(grafana_alerting_request_duration_seconds_bucket{namespace=\"$namespace\"} [5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(grafana_alerting_request_duration_seconds_bucket{namespace=\"$namespace\"} [5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(grafana_alerting_request_duration_seconds_bucket{namespace=\"$namespace\"} [5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Alert Rule Evaluation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grafana_alerting_rule_evaluations_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_annotations{namespace=\"$namespace\"})",
     "legendFormat": "Annotations"
    }
   ]
  },
  {
   "title": "Alert Rule Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grafana_alerting_rule_evaluations_total{namespace=\"$namespace\"}[$__rate_interval]))\n \n - \n \n sum(rate(grafana_alerting_rule_evaluation_failures_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "success"
    },
    {
     "expr": " sum(rate(grafana_alerting_rule_evaluation_failures_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Alerting Scheduler Behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(grafana_alerting_scheduler_behind_seconds{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerting Notification Latency",
   "type": "timeseries",
   "description": "The number of seconds taken to send notifications for firing and resolved alerts. This metric lets you observe slow or over-utilized integrations, such as an SMTP server that is being given emails faster than it can send them",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  grafana_alerting_notification_latency_seconds_bucket{namespace=\"$namespace\"}\n))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  grafana_alerting_notification_latency_seconds_bucket{namespace=\"$namespace\"}\n))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (\n  grafana_alerting_notification_latency_seconds_bucket{namespace=\"$namespace\"}\n))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})  ",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})  ",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container!=\"\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "throttling - {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collections (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(go_gc_duration_seconds_count{namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(process_open_fds{namespace=\"$namespace\"})",
     "legendFormat": "Open FDs (process)"
    },
    {
     "expr": "max(container_file_descriptors{namespace=\"$namespace\", container!=\"\"})",
     "legendFormat": "Open FDs (container)"
    }
   ]
  },
  {
   "title": "GC Durations (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(go_gc_duration_seconds_sum{namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Plugin Request Tail Latencies By Endpoint (q0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grafana_plugin_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (plugin_id, endpoint, le))",
     "legendFormat": "{{plugin_id}} - {{endpoint}} - q0.99"
    }
   ]
  },
  {
   "title": "HTTP Requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grafana_http_request_in_flight{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(grafana_live_node_num_users{namespace=\"$namespace\"})",
     "legendFormat": "Active (Live)"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "HTTP Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "HTTP traffic (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (handler, method, status_code) (\n  rate(grafana_http_request_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{method}} {{handler}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP volume per replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(grafana_http_request_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval])\n)\n/ scalar(count(grafana_build_info{namespace=\"$namespace\"}))",
     "legendFormat": "Volume"
    },
    {
     "expr": "count(grafana_build_info{namespace=\"$namespace\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Top slowest handlers (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5,\n  histogram_quantile(0.99,\n    sum by (method, handler, le) (\n      rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])\n    )\n  )\n)",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Datasource Request Duration (50th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(increase(grafana_datasource_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le, datasource) > 0)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Datasource Request Duration (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(grafana_datasource_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le, datasource) > 0)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Datasource Request Duration (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(grafana_datasource_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le, datasource) > 0)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Datasource Connection Tracking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(net_conntrack_dialer_conn_established_total{namespace=\"$namespace\"}[$__rate_interval])) by (dialer_name)",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Instance network traffic",
   "type": "timeseries",
   "description": "Shows raw network tx/rx from the instance pod(s). Transmit is positive, Receive is negative, in order to visually separate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "tx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    { "expr": "vector(0)", "legendFormat": "zero" }
   ]
  },
  {
   "title": "HTTP volume & latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "HTTP latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\r\n  rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])\r\n))",
     "legendFormat": "p99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\r\n  rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])\r\n))\r\n",
     "legendFormat": "p75 Latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (\r\n  rate(grafana_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])\r\n))\r\n",
     "legendFormat": "p50 Latency"
    }
   ]
  },
  {
   "title": "Dashboard Load Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(grafana_api_dashboard_get_milliseconds{namespace=\"$namespace\",quantile=\"0.5\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(grafana_api_dashboard_get_milliseconds{namespace=\"$namespace\",quantile=\"0.9\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(grafana_api_dashboard_get_milliseconds{namespace=\"$namespace\",quantile=\"0.99\"})",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Latency Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(go_sql_stats_connections_open{namespace=\"$namespace\"})",
     "legendFormat": "Open Connections"
    },
    {
     "expr": "sum(rate(go_sql_stats_connections_blocked_seconds{namespace=\"$namespace\"}[$__rate_interval])) ",
     "legendFormat": "Time spent waiting for a connection"
    }
   ]
  },
  {
   "title": "Closed DB Connections",
   "type": "timeseries",
   "description": "Lists the closed DB connections (per second) from Grafana to the Instance DB server, and the reasons why they were closed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_sql_stats_connections_closed_max_lifetime{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "max lifetime"
    },
    {
     "expr": "sum(rate(go_sql_stats_connections_closed_max_idle{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "max idle"
    },
    {
     "expr": "sum(rate(go_sql_stats_connections_closed_max_idle_time{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "max idle time"
    }
   ]
  },
  {
   "title": "Open/Idle DB Connections",
   "type": "timeseries",
   "description": "Lists the _total_ open/idle DB connections from Grafana to the Instance DB server. Note that this is a `sum`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_sql_stats_connections_idle{namespace=\"$namespace\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(go_sql_stats_connections_in_use{namespace=\"$namespace\"})",
     "legendFormat": "in use"
    }
   ]
  },
  {
   "title": "Time waiting for blocked DB connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_sql_stats_connections_blocked_seconds{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alerting state full sync duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } }
  },
  { "title": "Cache Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Query Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(rate(redis_keyspace_hits_total{namespace=\"$namespace\", container!=\"redis-alerting-server-exporter\"}[5m])) by (namespace, container)\n/\n(\nmax(rate(redis_keyspace_misses_total{namespace=\"$namespace\", container!=\"redis-alerting-server-exporter\"}[5m])) by (namespace, container)\n+\nmax(rate(redis_keyspace_hits_total{namespace=\"$namespace\", container!=\"redis-alerting-server-exporter\"}[5m])) by (namespace, container)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Query Cache Hit Ratio by Datasource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(grafana_caching_retrievals{response=\"hit\"}[$__rate_interval])) by (datasource)\n/\nsum(increase(grafana_caching_retrievals{}[$__rate_interval])) by (datasource)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}