{
 "title": "Ceph cluster",
 "description": "Overview of your Ceph cluster.",
 "tags": [
  "infrastructure",
  "rook-ceph",
  "ceph"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(ceph_pool_metadata,name)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status{}" }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr_bytes[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{} * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_wr_bytes{} * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_rd_bytes{} * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Alerts starting with Ceph",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_mon_metadata{})" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{}) or vector(0)"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{}) - count(ceph_osd_in{})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_up{})" }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in{})" }
   ]
  },
  {
   "title": "Total PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pg_total{})" }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})"
    }
   ]
  },
  { "title": "POOLS R/W", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (\r\n  sum by(pool_id) (\r\n    rate(ceph_pool_wr_bytes[$__rate_interval])\r\n  )\r\n  * on(pool_id) group_left(name)\r\n  ceph_pool_metadata{name=~\"${pool:regex}\"}\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (\r\n  sum by(pool_id) (\r\n    rate(ceph_pool_rd_bytes[$__rate_interval])\r\n  )\r\n  * on(pool_id) group_left(name)\r\n  ceph_pool_metadata{name=~\"${pool:regex}\"}\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CLUSTER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{}",
     "legendFormat": "Used"
    },
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_pool_rd[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr_bytes[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_pool_rd_bytes[5m]) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_avail_raw{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}} Avail"
    },
    {
     "expr": "(ceph_pool_stored_raw{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}} Stored"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{}) * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Device Classes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (device_class)(ceph_osd_metadata{})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts starting with Ceph",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"} OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Top Sluggish OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{} + ceph_osd_commit_latency_ms{}))",
       "legendFormat": "_auto"
      }
     ]
    },
    {
     "title": "Down OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_osd_up{} == 0 OR on() vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics (NodeExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_anon_bytes{}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(node_memory_Active_anon_bytes{})",
       "legendFormat": "Cluster Memory Usage"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(instance)(irate(node_cpu_seconds_total{job=\"node-exporter\",mode!=\"idle\"}[5m])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Network Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_network_transmit_bytes_total{job=\"node-exporter\",device!~\"lo|veth.*|cali.*|flannel.*|cni.*\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Network In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_network_receive_bytes_total{job=\"node-exporter\",device!~\"lo|veth.*|cali.*|flannel.*|cni.*\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Space in /var filesystem",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_free_bytes{job=\"node-exporter\", mountpoint=\"/var\", fstype!~\"tmpfs|overlay\"})*100 / (node_filesystem_size_bytes{job=\"node-exporter\", mountpoint=\"/var\", fstype!~\"tmpfs|overlay\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_active{})", "legendFormat": "Active" },
    { "expr": "sum(ceph_pg_clean{})", "legendFormat": "Clean" },
    { "expr": "sum(ceph_pg_peering{})", "legendFormat": "Peering" },
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    {
     "expr": "sum(ceph_pg_total{}) - sum(ceph_pg_clean{})",
     "legendFormat": "Unclean"
    },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
    { "expr": "sum(ceph_pg_forced_backfill{})", "legendFormat": "Forced Backfill" },
    { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_backfill_wait{})", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfilling{})", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
    {
     "expr": "sum(ceph_pg_backfill_toofull{})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" }
   ]
  },
  {
   "title": "Pool Recovery Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_recovering_objects_per_sec{} * on (pool_id) group_left(name) ceph_pool_metadata{name=~\"${pool:regex}\"})",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms{}" }
   ]
  },
  {
   "title": "Average OSD Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})",
     "legendFormat": "Apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_osd_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions (if present)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{}) OR on() vector(0)"
      }
     ]
    }
   ]
  }
 ]
}