{
 "title": "K8s: PVC and CSI storage",
 "description": "Kubernetes PVC and CSI storage usage from kubelet volume stats and kube-state-metrics.",
 "tags": [
  "infrastructure",
  "k8s",
  "storage",
  "pvc",
  "csi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "section",
    "label": "Section",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section!=\"\"}, label_pve_k8s_talos_section)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\"}, namespace)"
    }
   },
   {
    "name": "part_of",
    "label": "Part of",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of!=\"\"}, label_app_kubernetes_io_part_of)"
    }
   },
   {
    "name": "csi",
    "label": "CSI",
    "query": {
     "query": "label_values(kube_storageclass_info, provisioner)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component!=\"\"}, label_app_kubernetes_io_component)"
    }
   },
   {
    "name": "storage_role",
    "label": "Storage role",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role!=\"\"}, label_pve_k8s_talos_storage_role)"
    }
   },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Used storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Used %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) / clamp_min(sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})), 1)",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\",phase=\"Bound\"} == 1) * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "Bound"
    }
   ]
  },
  {
   "title": "PVCs >85%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((100 * kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} / clamp_min(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}, 1) > 85) * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) or on() vector(0)",
     "legendFormat": ">85%"
    }
   ]
  },
  {
   "title": "Abnormal volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kubelet_volume_stats_health_status_abnormal{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} == 1) * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) or on() vector(0)",
     "legendFormat": "Abnormal"
    }
   ]
  },
  {
   "title": "PVC used vs capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} used"
    },
    {
     "expr": "sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} capacity"
    }
   ]
  },
  {
   "title": "PVC used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) / clamp_min(sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})), 1)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC inode used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_inodes_used{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) / clamp_min(sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_inodes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})), 1)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC usage table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})) / clamp_min(sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})), 1)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC used bytes table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVCs not bound",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\",phase=~\"Pending|Lost\"} == 1) * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} {{phase}}"
    }
   ]
  },
  {
   "title": "Mounted PVCs by PVC labels",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (namespace,persistentvolumeclaim,pod,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) (kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) max by (namespace,persistentvolumeclaim,storageclass,provisioner,label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) ((kube_persistentvolumeclaim_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"} * on(namespace,persistentvolumeclaim) group_left(label_pve_k8s_talos_section,label_app_kubernetes_io_part_of,label_app_kubernetes_io_component,label_pve_k8s_talos_storage_role) kube_persistentvolumeclaim_labels{label_pve_k8s_talos_section=~\"$section\",label_app_kubernetes_io_part_of=~\"$part_of\",label_app_kubernetes_io_component=~\"$component\",label_pve_k8s_talos_storage_role=~\"$storage_role\"}) * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~\"$csi\"}))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} {{pod}}"
    }
   ]
  },
  {
   "title": "CSI StorageClasses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_storageclass_info{provisioner=~\"$csi\"})",
     "legendFormat": "StorageClasses"
    }
   ]
  },
  {
   "title": "CSI PVs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_info{csi_driver=~\"$csi\"})",
     "legendFormat": "PVs"
    }
   ]
  },
  {
   "title": "CSI attachments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_volumeattachment_status_attached * on(volumeattachment) group_left(attacher,node) kube_volumeattachment_info{attacher=~\"$csi\"})",
     "legendFormat": "Attached"
    }
   ]
  },
  {
   "title": "Unattached attachments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_volumeattachment_status_attached == 0) * on(volumeattachment) group_left(attacher,node) kube_volumeattachment_info{attacher=~\"$csi\"}) or on() vector(0)",
     "legendFormat": "Unattached"
    }
   ]
  },
  {
   "title": "CSI pods not ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"rook-ceph\",pod=~\".*csi.*\",condition=\"true\"} == 0) or on() vector(0)",
     "legendFormat": "Not ready"
    }
   ]
  },
  {
   "title": "CSI restarts in range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"rook-ceph\",pod=~\".*csi.*\"}[$__range]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "CSI operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (driver_name,method_name,grpc_status_code) (rate(csi_operations_seconds_count{driver_name=~\"$csi\"}[$__rate_interval]))",
     "legendFormat": "{{driver_name}} {{method_name}} {{grpc_status_code}}"
    }
   ]
  },
  {
   "title": "CSI operation latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,driver_name,method_name) (rate(csi_operations_seconds_bucket{driver_name=~\"$csi\"}[$__rate_interval]))) >= 0",
     "legendFormat": "p99 {{driver_name}} {{method_name}}"
    }
   ]
  },
  {
   "title": "CSI StorageClasses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_storageclass_info{provisioner=~\"$csi\"}",
     "legendFormat": "{{storageclass}}"
    }
   ]
  },
  {
   "title": "CSI volume attachments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_volumeattachment_status_attached * on(volumeattachment) group_left(attacher,node) kube_volumeattachment_info{attacher=~\"$csi\"} * on(volumeattachment) group_left(volumename) kube_volumeattachment_spec_source_persistentvolume",
     "legendFormat": "{{volumeattachment}}"
    }
   ]
  }
 ]
}