{
 "title": "Keycloak Troubleshooting",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{container=\"keycloak\"}, namespace)"
    }
   },
   {
    "name": "jdbc_cache_names",
    "query": "realms,users,keys,authorization"
   },
   {
    "name": "caffeine_cache",
    "query": {
     "query": "label_values(cache_evictions_count{namespace=\"$namespace\",container=\"keycloak\"}, cache)"
    }
   },
   { "name": "ispn_local_cache", "query": "crl" },
   {
    "name": "ispn_clustered_caches",
    "query": {
     "query": "label_values(vendor_rpc_manager_replication_count{namespace=\"$namespace\",container=\"keycloak\"}, cache)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SLO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  sum (up{\n    container=\"keycloak\", \n    namespace=\"$namespace\"\n  } > 0)[$__range:$__interval]\n)\n/\ncount_over_time(vector(1)[$__range:$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses below 250ms",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_server_requests_seconds_bucket{\n      uri=~\"/realms/{realm}/protocol/{protocol}/.*|/realms/{realm}/login-actions/.*\", \n      le=\"0.25\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n) without (le,uri,status,outcome,method,pod,instance) \n/\nsum(\n  rate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}/.*|/realms/{realm}/login-actions/.*\", \n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [$__range] \n  )\n) without (le,uri,status,outcome,method,pod,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error responses",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions.*\", \n      outcome=\"SERVER_ERROR\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n) or vector(0) \n/\nsum(\n  rate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions.*\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes in % of responses below 250ms",
   "type": "timeseries",
   "description": "This Prometheus query calculates the percentage of authentication requests that completed within 0.25 seconds relative to all authentication requests for specific Keycloak endpoints, targeting a particular namespace and pod, over the past 5 minutes.",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  irate(\n    http_server_requests_seconds_bucket{\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions.*\", \n      le=\"0.25\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [5m] \n  )\n) without (le,uri,status,outcome,method,instance) \n/\nsum(\n  irate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions.*\", \n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n) without (le,uri,status,outcome,method,instance)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\n  irate(\n    http_server_requests_seconds_bucket{\n      uri=~\"/realms/{realm}/protocol/{protocol}/.*|/realms/{realm}/login-actions/.*\", \n      le=\"0.25\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [5m] \n  )\n) without (le,uri,status,outcome,method,pod,instance) \n/\nsum(\n  irate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}/.*|/realms/{realm}/login-actions/.*\", \n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n) without (le,uri,status,outcome,method,pod,instance)",
     "legendFormat": "All pods"
    }
   ]
  },
  {
   "title": "Changes in % of Error responses",
   "type": "timeseries",
   "description": "This Prometheus query calculates the percentage of authentication requests that returned a server side error for all authentication requests, targeting a particular namespace, over the past 5 minutes.",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri)\n(\n  rate(\n    http_server_requests_seconds_count{\n      outcome=\"SERVER_ERROR\",\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions/.*\", \n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [5m] \n  )\n)\n/\nsum by (uri)\n(\n  rate(\n    http_server_requests_seconds_count{\n      uri=~\"/realms/{realm}/protocol/{protocol}.*|/realms/{realm}/login-actions/.*\", \n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Info",
     "type": "table",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 2538 },
     "targets": [
      {
       "expr": "max(jvm_info_total{namespace=\"$namespace\"}) by (pod, vendor, runtime, version)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KUBERNETES - CPU Usage percentage",
     "type": "timeseries",
     "description": "This is available only in Kubernetes and only if your pods have cpu limits set",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 2538 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"keycloak\", namespace=\"$namespace\"}[5m])) by (pod)\n/\non(pod) group_left\nsum(kube_pod_container_resource_limits{container=\"keycloak\", namespace=\"$namespace\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average memory usage",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 2538 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by (pod) (jvm_memory_used_bytes{namespace=\"$namespace\"}))[$__range:$__interval]) / count_over_time((sum by (pod) (jvm_memory_used_bytes{namespace=\"$namespace\"}))[$__range:$__interval]) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM memory used vs committed",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 2554 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_memory_used_bytes{namespace=\"$namespace\"})",
       "legendFormat": "{{pod}} - used"
      },
      {
       "expr": "sum by (pod) (jvm_memory_committed_bytes{namespace=\"$namespace\"})",
       "legendFormat": "{{pod}} - committed"
      }
     ]
    },
    {
     "title": "Average GC time",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 2554 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {},
      {
       "expr": "sum(\n  rate(\n    jvm_gc_pause_seconds_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n) without (action,instance,cause) \n/\nsum(\n  rate(\n    jvm_gc_pause_seconds_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [$__range] \n  )\n) without (action,instance,cause)",
       "legendFormat": "{{pod}} - {{gc}}"
      }
     ]
    },
    {
     "title": "Changes in average GC times in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 2554 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod,cause)(irate(jvm_gc_pause_seconds_sum{container=\"keycloak\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}} - {{cause}}"
      }
     ]
    },
    {
     "title": "Number of GC events in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 2570 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod,cause)(irate(jvm_gc_pause_seconds_count{container=\"keycloak\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}} - {{cause}}"
      }
     ]
    },
    {
     "title": "Maximum GC time and cause",
     "type": "timeseries",
     "description": "I am not sure about this metric. I would expect _max to be only increasing number while here it is going up and down so I am not sure what this really means",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 2570 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod,cause) (jvm_gc_pause_seconds_max{container=\"keycloak\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}} - {{cause}}"
      }
     ]
    },
    {
     "title": "JVM GC CPU overhead %",
     "type": "timeseries",
     "description": "The percentage of CPU time spent on garbage collection, indicating the impact of GC on application performance in the JVM. It refers to the proportion of the total CPU processing time that is dedicated to executing garbage collection (GC) operations, as opposed to running application code or performing other tasks. This metric helps determine how much overhead GC introduces, affecting the overall performance of the Keycloak’s JVM.",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 2570 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_gc_overhead{container=\"keycloak\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM waiting threads",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 2586 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod)(jvm_threads_states_threads{namespace=\"$namespace\", container=\"keycloak\", state=\"waiting\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 2586 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{namespace=\"$namespace\", container=\"keycloak\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection pool utilization %",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7970 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (pod) (sum_over_time(agroal_active_count{namespace=\"$namespace\"}[$__range:$__interval]) / sum_over_time((agroal_active_count{namespace=\"$namespace\"} + agroal_available_count{namespace=\"$namespace\"})[$__range:$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Threads waiting for database connection",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 7970 },
     "targets": [
      {
       "expr": "agroal_awaiting_count{container=\"keycloak\", namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Database connections pool",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 7970 },
     "targets": [
      {
       "expr": "agroal_available_count{job=~\"${namespace}/keycloak-metrics|keycloak-service\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} - available connections"
      },
      {
       "expr": "agroal_active_count{job=~\"${namespace}/keycloak-metrics|keycloak-service\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} - used connections"
      }
     ]
    },
    {
     "title": "Number of acquired connections in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7986 },
     "targets": [
      {
       "expr": "sum by (pod)(irate(agroal_acquire_count_total{container=\"keycloak\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 7561 },
     "targets": [
      {
       "expr": "sum by (pod) (\n  irate(\n    http_server_requests_seconds_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of requests per URI and outcome",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 6, "y": 7561 },
     "targets": [
      {
       "expr": "sum by (uri,outcome) (http_server_requests_seconds_count{container=\"keycloak\", namespace=\"$namespace\"})",
       "legendFormat": "{{uri}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "All requests with processing time",
     "type": "heatmap",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 7576 },
     "targets": [
      {
       "expr": "sum by (le) (idelta(http_server_requests_seconds_bucket{container=\"keycloak\", namespace=\"$namespace\"} [5m]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total number of requests per URI and outcome in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 6, "y": 7576 },
     "targets": [
      {
       "expr": "sum by (uri,outcome) (irate(http_server_requests_seconds_count{container=\"keycloak\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{uri}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Active requests",
     "type": "timeseries",
     "description": "The current number of active requests processed by each pod",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 7591 },
     "targets": [
      {
       "expr": "sum by (pod) (http_server_active_requests{container=\"keycloak\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Changes in outcome types in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 6, "y": 7591 },
     "targets": [
      {
       "expr": "sum by (pod,outcome) (irate(http_server_requests_seconds_count{container=\"keycloak\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Changes in response sizes in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 7606 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod)(\n  irate(\n    http_server_bytes_written_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [5m] \n  )\n)\n/\nsum by (pod)(\n  irate(\n    http_server_bytes_written_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average response size",
     "type": "stat",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 7606 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod)(\n  rate(\n    http_server_bytes_written_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n)\n/\nsum by(pod)(\n  rate(\n    http_server_bytes_written_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [$__range] \n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average request size",
     "type": "stat",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 7606 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod)(\n  rate(\n    http_server_bytes_read_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [$__range] \n  )\n)\n/\nsum by(pod)(\n  rate(\n    http_server_bytes_read_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [$__range] \n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Changes in request sizes in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 7621 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod)(\n  irate(\n    http_server_bytes_read_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\"}\n    [5m] \n  )\n)\n/\nsum by (pod)(\n  irate(\n    http_server_bytes_read_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\"}\n    [5m] \n  )\n)",
       "legendFormat": "{{pod}} - requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Size",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 2541 },
     "targets": [
      {
       "expr": "vendor_cluster_size{namespace=\"$namespace\", container=\"keycloak\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Response Time (99th)",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 2541 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, node, target_node) (rate(vendor_jgroups_stats_sync_requests_seconds_bucket{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval])))",
       "legendFormat": "{{node}} -> {{target_node}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 2541 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vendor_jgroups_stats_sync_requests_seconds_sum{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval]) / (rate(vendor_jgroups_stats_sync_requests_seconds_count{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval]))",
       "legendFormat": "{{node}} -> {{target_node}}"
      }
     ]
    },
    {
     "title": "Message Retransmissions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 2556 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_jgroups_unicast3_get_num_xmits{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Messages Dropped",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 2556 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_jgroups_red_get_dropped_messages{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 2556 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_jgroups_tcp_get_num_msgs_sent{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval])",
       "legendFormat": "{{node}} Sent"
      },
      {
       "expr": "rate(vendor_jgroups_tcp_get_num_msgs_received{namespace=\"$namespace\", container=\"keycloak\"}[$__rate_interval]) * -1",
       "legendFormat": "{{node}} Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Database caching - $jdbc_cache_names",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "jdbc_cache_names",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of owned entries",
     "type": "timeseries",
     "description": "The approximate number of entries stored by the node, excluding backup copies.",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 6642 },
     "targets": [
      {
       "expr": "sum by (pod)(vendor_statistics_approximate_entries_unique{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of all stored entries (including backups)",
     "type": "timeseries",
     "description": "The approximate number of entries stored by the node, including backup copies.",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 6642 },
     "targets": [
      {
       "expr": "sum by (pod)(vendor_statistics_approximate_entries_unique{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of evictions in 5 minutes interval",
     "type": "timeseries",
     "description": "Eviction is the process to limit the cache size and, when full, an entry is removed to make room for a new entry to be cached. As Keycloak caches the database entities in the users, realms and authorization, database access always proceeds with an eviction event.\n\nA rapid increase of eviction and very high database CPU usage means the users or realms cache is too small for smooth Keycloak operation, as data needs to be re-loaded very often from the database which slows down responses. If enough memory is available, consider increasing the max cache size using the CLI options cache-embedded-users-max-count or cache-embedded-realms-max-count",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 6642 },
     "targets": [
      {
       "expr": "sum by (pod)(irate(vendor_statistics_evictions{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of write operations in 5 minutes interval",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 6657 },
     "targets": [
      {
       "expr": "sum by (pod)(irate(vendor_statistics_store_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Read/Write ratio",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 6657 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (pod)((\nirate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) + irate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))\n/\n(\n    irate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) + irate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m])\n    + \n    irate(vendor_statistics_remove_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) + irate(vendor_statistics_remove_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) \n    + \n    irate(vendor_statistics_store_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m])\n))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average write operation time",
     "type": "stat",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 6657 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (pod)(\n  rate(\n    vendor_statistics_store_times_seconds_sum{\n      container=\"keycloak\", \n      namespace=\"$namespace\",\n      cache=\"$jdbc_cache_names\"}\n    [$__range] \n  )\n)\n/\nsum by(pod)(\n  rate(\n    vendor_statistics_store_times_seconds_count{\n      container=\"keycloak\",\n      namespace=\"$namespace\",\n      cache=\"$jdbc_cache_names\"}\n    [$__range] \n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of read operations in 5 minutes interval",
     "type": "timeseries",
     "description": "A read operation reads a value from the cache. It divides into two groups, a hit if a value is found, and a miss if not found.",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 6672 },
     "targets": [
      {
       "expr": "sum by (pod) (irate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) + irate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache read hit/miss ratio",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 6672 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (pod)(irate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", cache=\"$jdbc_cache_names\", namespace=\"$namespace\"}[5m]) / (irate(vendor_statistics_hit_times_seconds_count{cache=\"$jdbc_cache_names\", namespace=\"$namespace\", container=\"keycloak\"}[5m]) + irate(vendor_statistics_miss_times_seconds_count{cache=\"$jdbc_cache_names\", namespace=\"$namespace\", container=\"keycloak\"}[5m])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of cache read misses in 5 minute interval",
     "type": "timeseries",
     "description": "A read operation reads a value from the cache. It divides into two groups, a hit if a value is found, and a miss if not found.",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 6672 },
     "targets": [
      {
       "expr": "sum by (pod) (irate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of remove operations in 5 minutes interval",
     "type": "timeseries",
     "description": "A remove operation removes a value from the cache. It divides in two groups, a hit if a value exists, and a miss if the value does not exist.",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 6687 },
     "targets": [
      {
       "expr": "sum by (pod)(irate(vendor_statistics_remove_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]) + irate(vendor_statistics_remove_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache remove hit/miss ratio",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 6687 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (pod)(irate(vendor_statistics_remove_hit_times_seconds_count{container=\"keycloak\", cache=\"$jdbc_cache_names\", namespace=\"$namespace\"}[5m]) / (irate(vendor_statistics_remove_hit_times_seconds_count{cache=\"$jdbc_cache_names\", namespace=\"$namespace\", container=\"keycloak\"}[5m]) + irate(vendor_statistics_remove_miss_times_seconds_count{cache=\"$jdbc_cache_names\", namespace=\"$namespace\", container=\"keycloak\"}[5m])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of cache remove misses in 5 minutes interval",
     "type": "timeseries",
     "description": "A remove operation removes a value from the cache. It divides in two groups, a hit if a value exists, and a miss if the value does not exist.",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 6687 },
     "targets": [
      {
       "expr": "sum by (pod) (irate(vendor_statistics_remove_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$jdbc_cache_names\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Local caching - $caffeine_cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "caffeine_cache",
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "cache_size{namespace=\"$namespace\", container=\"keycloak\", cache=\"$caffeine_cache\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(cache_gets_total{namespace=\"$namespace\", container=\"keycloak\", cache=\"$caffeine_cache\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(rate(cache_gets_total{namespace=\"$namespace\", container=\"keycloak\", cache=\"$caffeine_cache\", result=\"hit\"}[$__rate_interval]))\n/ \n(rate(cache_gets_total{namespace=\"$namespace\", container=\"keycloak\", cache=\"$caffeine_cache\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(cache_evictions_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$caffeine_cache\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Local caching - $ispn_local_cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "ispn_local_cache",
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 33978 },
     "targets": [
      {
       "expr": "vendor_statistics_approximate_entries{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 33978 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval]) + (rate(vendor_statistics_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 33978 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  rate(vendor_statistics_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval])\n) / (\n rate(vendor_statistics_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval]) +\n rate(vendor_statistics_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval])\n) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 33992 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_evictions{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_local_cache\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clustered caching - $ispn_clustered_caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "ispn_clustered_caches",
   "collapsed": true,
   "panels": [
    {
     "title": "Cache size",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 81350 },
     "targets": [
      {
       "expr": "vendor_statistics_approximate_entries{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Replication Time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 81350 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vendor_rpc_manager_average_replication_time{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Read Write Ratio",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 81350 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\nrate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\nrate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n)\n/\n(\nrate(vendor_statistics_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\nrate(vendor_statistics_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\nrate(vendor_statistics_remove_hit_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) + \nrate(vendor_statistics_remove_miss_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) + \nrate(vendor_statistics_store_times_seconds_count{container=\"keycloak\", namespace=\"$namespace\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 81420 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_store_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Writes Times",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 81420 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  rate(vendor_statistics_store_times_seconds_sum{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n) / (\n  rate(vendor_statistics_store_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 81420 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_evictions{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 81434 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) + (rate(vendor_statistics_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reads Times",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 81434 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  rate(vendor_statistics_hit_times_seconds_sum{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\n  rate(vendor_statistics_miss_times_seconds_sum{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n) / (\n  rate(vendor_statistics_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\n  rate(vendor_statistics_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Removes",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 81448 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(vendor_statistics_remove_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) + (rate(vendor_statistics_remove_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Removes Times",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 81448 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  rate(vendor_statistics_remove_hit_times_seconds_sum{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\n  rate(vendor_statistics_remove_miss_times_seconds_sum{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n) / (\n  rate(vendor_statistics_remove_hit_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval]) +\n  rate(vendor_statistics_remove_miss_times_seconds_count{namespace=\"$namespace\", container=\"keycloak\", cache=\"$ispn_clustered_caches\"}[$__rate_interval])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}